version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.22
    - 14.14.24
    - 14.14.26
    - 14.14.28
    - 14.14.30
    - 14.14.35
    - 15.0.0
  - dependency-name: typescript
    versions:
    - 4.1.4
    - 4.1.5
  - dependency-name: vscode-test
    versions:
    - 1.5.0
